### ISSUE TITLE
smithctl kill should accept a group

### ISSUE THREAD

**Issue by mpalmer** [filterfish/smith2#16]
If one could do `smithctl kill -g <group>`, and have any agents in the specified group (that weren't stopped) receive that signal, it would make it a lot easier to "force cleanup" misbehaving agents on deploy.

**Comment by qnm** [comment]
Looks like this functionality has been added in f428a85034e6ac6e437047d57f5f1afb40db09b8.

@filterfish I think you can close this.

```
smithctl kill --help
  Kill an agent/agents.

  Usage:
    smithctl kill [Options] <uuid[s]>

[Options] are:

  -g, --group=<s>    kill agents in this group
```
