### ISSUE TITLE
Enable Dynamic Smith Config

### ISSUE THREAD

**Issue by DylanGriffith** [filterfish/smith2#20]
It would be useful to have a way of starting smith without needing a .smithrc. This would mean that `require 'smith'` would not raise if it couldn't find a '.smithrc', but perhaps could still try. A client may do something like:
```ruby
require 'smith'
Smith.configure(my_smith_options)
```

**Comment by filterfish** [comment]
Smith now has a sensible default config and the rest can be set using environment variables. The only config that needs to be set are:

* `agency.acl_directories`
* `agency.agent_directories`

which can also be set using the environment variables:

* `SMITH_ACL_DIRECTORIES`
* `SMITH_AGENT_DIRECTORIES`

respectively.
