### ISSUE TITLE
"Stack level too deep" error if no .smithrc is found

### ISSUE THREAD

**Issue by mpalmer** [filterfish/smith2#38]
If you run `smithctl list -la` in a directory outside of the filesystem subtree whose root contains a `.smithrc` file, the attempt will bomb with `/usr/local/bin/smithctl:23: stack level too deep (SystemStackError)`.

**Comment by filterfish** [comment]
smith now only checks for `.smithrc` in the local directory, `$HOME`, `/etct/smithrc` and `/etc/smith/smithrc`.
