### ISSUE TITLE
Acking message twice breaks in a weird way

### ISSUE THREAD

**Issue by DylanGriffith** [filterfish/smith2#43]
When an agent acks a message twice it puts the agent in a strange state. The agency still thinks the agent is running but rabbitmq says there are no consumers. The logs don't say anything particular about it. You described this to me as a channel error and said smith should "blow up" under those circumstances.

**Comment by filterfish** [comment]
Smith exposes the behaviour of the AMQP gem which I think is correct so I'm closing this with a won't fix.
